apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-sidecar-injector-webhook-configmap
  namespace: default
data:
  sidecarconfig.yaml: |
    policy: enabled
    containers:
    - name: perf-sidecar
      image: alicek106/perf-sidecar
      imagePullPolicy: IfNotPresent
      stdin: true
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
      - name: perf-output
        mountPath: /out
      args: ["record", "0", "60", "1", "-g"]
    volumes:
    - name: perf-output
      hostPath:
        path: /out
        type: DirectoryOrCreate
    ShareProcessNamespace: true
