apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: perf-sidecar-injector-webhook-cfg
  labels:
    app: perf-sidecar-injector
webhooks:
- name: sidecar-injector.perf.local
  clientConfig:
    service:
      name: perf-sidecar-injector-webhook-svc
      namespace: default
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
  rules:
    - operations: [ "CREATE" ]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injector: enabled

  # 1.13+ 에서는 None or onDryRun만 가능. 이 admission controller가 추가적인 사이드 이펙트를 가지는지를 판단한다.
  # ex) admission controller가 tls 인증서를 만들거나 하면 사이드 이펙트가 존재하는 것임. 이럴 때는 side effect가 존재함을 명시함으로써
  # dry run 같은걸 못하도록 API 서버단에서 막을 수 있다. (server side dry-run을 하면 admission controller도 거치기 때문에..)
  sideEffects: None 
  admissionReviewVersions: ["v1beta1"] # v1, v1beta1을 동시에 써주면 에러가 발생한다.
